### ISSUE TITLE
NOT WORKING WITH SUBMIT BUTTON

### ISSUE THREAD

**Issue by sourabhtiwari** [KMontag42/sweetalert2-rails#2]
THANKS FOR THE GOOD WORK.SWEET ALERT IS JUST AWSOME.I WOULD LOVE TO USE IT IN MY PROJECTS BUT I AM STUCK ON DOUBT WITH SUBMIT BUTTON.

ON SUBMIT BUTTON CLICK IT AUTOMATICALLY DISAPPEARS WITHOUT CONFIRMATION

**Comment by KMontag42** [comment]
could you send me the code you are using?
