### ISSUE TITLE
Still using SweetAlert2 4.0.11 when SweetAlert2 is currently on 6.6.6

### ISSUE THREAD

**Issue by joeyparis** [KMontag42/sweetalert2-rails#4]

**Comment by sabatesduran** [comment]
I made a PR #5 

If you need it now we did a fork for my company: https://github.com/trinity-tech/sweetalert2-rails

**Comment by KMontag42** [comment]
Apologies for this taking so-damn-long. I had stepped away from the Rails world for a bit. But I'm back baby!!

We are now current with 7.25.6 :)
